agents/urls.py
from django.urls import path
from .views import (
    AgentListView, AgentCreateView, AgentDetailView, 
    AgentUpdateView, AgentDeleteView
)

app_name = 'agents'

urlpatterns = [
    path('', AgentListView.as_view(), name='agent-list'),
    path('<int:pk>/', AgentDetailView.as_view(), name='agent-detail'),
    path('<int:pk>/update/', AgentUpdateView.as_view(), name='agent-update'),
    path('<int:pk>/delete/', AgentDeleteView.as_view(), name='agent-delete'),
    path('create/', AgentCreateView.as_view(), name='agent-create'),
]

djcrm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import (
    LoginView, 
    LogoutView, 
    PasswordResetView, 
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView
)
from django.urls import path, include
from leads.views import AdminLogin, landing_page, LandingPageView, SignupView, DashboardView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LandingPageView.as_view(), name='landing-page'),
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
    path('leads/',  include('leads.urls', namespace="leads")),
    path('agents/',  include('agents.urls', namespace="agents")),
    path('signup/', SignupView.as_view(), name='signup'),
    path('reset-password/', PasswordResetView.as_view(), name='reset-password'),
    path('password-reset-done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('login/', AdminLogin.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

leads/urls.py
from django.urls import path
from .views import (
    LeadListView, LeadDetailView, LeadCreateView, LeadUpdateView, LeadDeleteView,
    AssignAgentView, CategoryListView, CategoryDetailView, LeadCategoryUpdateView,
    CategoryCreateView, CategoryUpdateView, CategoryDeleteView, LeadJsonView, 
    FollowUpCreateView, FollowUpUpdateView, FollowUpDeleteView
)

app_name = "leads"

urlpatterns = [
    path('', LeadListView.as_view(), name='lead-list'),
    path('json/', LeadJsonView.as_view(), name='lead-list-json'),
    path('<int:pk>/', LeadDetailView.as_view(), name='lead-detail'),
    path('<int:pk>/update/', LeadUpdateView.as_view(), name='lead-update'),
    path('<int:pk>/delete/', LeadDeleteView.as_view(), name='lead-delete'),
    path('<int:pk>/assign-agent/', AssignAgentView.as_view(), name='assign-agent'),
    path('<int:pk>/category/', LeadCategoryUpdateView.as_view(), name='lead-category-update'),
    path('<int:pk>/followups/create/', FollowUpCreateView.as_view(), name='lead-followup-create'),
    path('followups/<int:pk>/', FollowUpUpdateView.as_view(), name='lead-followup-update'),
    path('followups/<int:pk>/delete/', FollowUpDeleteView.as_view(), name='lead-followup-delete'),
    path('create/', LeadCreateView.as_view(), name='lead-create'),
    path('categories/', CategoryListView.as_view(), name='category-list'),
    path('categories/<int:pk>/', CategoryDetailView.as_view(), name='category-detail'),
    path('categories/<int:pk>/update/', CategoryUpdateView.as_view(), name='category-update'),
    path('categories/<int:pk>/delete/', CategoryDeleteView.as_view(), name='category-delete'),
    path('create-category/', CategoryCreateView.as_view(), name='category-create'),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>DJCRM</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
</head>

<body>
    {% include 'navbar.html' %}

    <div class="container">
            {% include 'messages.html' %}
            {% block content %}
            {% endblock content %}
    </div>

    {% include "scripts.html" %}
</body>

</html>

templates/dashboard.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<section class="text-gray-700 body-font">
    <div class="container mx-auto flex px-5 py-24 items-center justify-center flex-col">
      <div class="text-center lg:w-2/3 w-full">
        <h1 class="title-font sm:text-4xl text-3xl mb-4 font-medium text-gray-900">
            CRM Dashboard
        </h1>
    
        <div class="flex flex-wrap -m-4 text-center">
            <div class="p-4 md:w-1/3 sm:w-1/2 w-full">
                <div class="border-2 border-gray-200 px-4 py-6 rounded-lg">
                <h2 class="title-font font-medium text-3xl text-gray-900">{{ total_lead_count }}</h2>
                <p class="leading-relaxed">Total Leads</p>
                </div>
            </div>
            <div class="p-4 md:w-1/3 sm:w-1/2 w-full">
                <div class="border-2 border-gray-200 px-4 py-6 rounded-lg">
                <h2 class="title-font font-medium text-3xl text-gray-900">{{ total_in_past30 }}</h2>
                <p class="leading-relaxed">Leads added in last 30 days</p>
                </div>
            </div>
            <div class="p-4 md:w-1/3 sm:w-1/2 w-full">
                <div class="border-2 border-gray-200 px-4 py-6 rounded-lg">
                <h2 class="title-font font-medium text-3xl text-gray-900">{{ converted_in_past30 }}</h2>
                <p class="leading-relaxed">Converted in last 30 days</p>
                </div>
            </div>
        </div>
        
      </div>
    </div>
</section>
{% endblock content %}

templates/landing.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="row">
  <p>
    This CRM helps you manage your leads.
  </p>
</div>
<div class="row">

  <div class="row">
    <a href="{% url 'login' %}">
      Login to get started
    </a>
  </div>
</div>
{% endblock content %}

templates/messages.html
{% if messages %}
    {% for message in messages %}
        
            <p>
                {{ message }}
            </p>
    {% endfor %}
{% endif %}

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav"
    aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      {% if not request.user.is_authenticated %}
      <li class="nav-item">
        <a href="{% url 'signup' %}" class="nav-link">Signup</a>
      </li>
      {% else %}
        {% if request.user.is_organisor %}
        <li class="nav-item">
          <a href="{% url 'agents:agent-list' %}" class="nav-link">Agents</a>
        </li>
        {% endif %}
        <li class="nav-item">
          <a href="{% url 'leads:lead-list' %}" class="nav-link">Leads</a>
        </li>
      {% endif %}


      {% if request.user.is_authenticated %}
      <li class="nav-item">
        <a href="{% url 'logout' %}" class="nav-link">
          Logout: {{ request.user.username }}
        </a>
      </li>
      {% else %}
      <li class="nav-item">
        <a href="{% url 'login' %}" class="nav-link">
          Login
        </a>
      </li>
      {% endif %}
    </ul>
  </div>
</nav>

templates/scripts.html
{% load static %}

<script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>